### ISSUE TITLE
GPU implementation of powerlaw fit

### ISSUE THREAD

**Issue by cdhinrichs** [CalculatedContent/WeightWatcher#195]
Currently, most of the time taken by a call to `WeightWatcher.analyze()` is taken up by calls to `powerlaw.Fit()`:
```
   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.002    0.002   16.866   16.866 weightwatcher.py:2070(analyze)
        1    0.000    0.000   16.410   16.410 weightwatcher.py:1899(apply_fit_powerlaw)
        1    0.000    0.000   16.410   16.410 weightwatcher.py:2675(fit_powerlaw)
     2050    0.009    0.000   16.258    0.008 powerlaw.py:582(__init__)
     2050    0.034    0.000   16.134    0.008 powerlaw.py:623(fit)
        1    0.000    0.000   14.494   14.494 weightwatcher.py:2696(pl_fit)
```
As can be seen in the left most column, much of this time is taken by M=2048 + 2 calls to the `powerlaw Distribution.fit` method for each possible xmin, each of which is entirely independent, and hence parallelizable. Furthermore, much of the `powerlaw` code itself deals with special cases that never arise in weightwatcher. Hence, a lightweight reimplementation of `powerlaw` making use of GPU parallelization would greatly speed up the `WeightWatcher.analyze()` method.

The proposed solution is to create a `Fit` shim class which, if GPU is not available, would default to the `powerlaw.Fit` class. This class would have to match the relevant portions of the Fit calling API. In `weightwatcher.py`, it is used in the following ways:

The single entry point for creating it is:
```python
        def pl_fit(data=None, xmin=None, xmax=None, verbose=False, distribution=POWER_LAW):
            f = io.StringIO()
            with redirect_stdout(f), redirect_stderr(f), warnings.catch_warnings():
                warnings.simplefilter(action='ignore', category=RuntimeWarning)
                return powerlaw.Fit(data, xmin=xmin, xmax=xmax, verbose=verbose, distribution=distribution, xmin_distribution=distribution)

        def pl_compare(fit, dist):
            f = io.StringIO()
            with redirect_stdout(f), redirect_stderr(f), warnings.catch_warnings():
                warnings.simplefilter(action='ignore', category=RuntimeWarning)
                return fit.distribution_compare(dist, TRUNCATED_POWER_LAW, normalized_ratio=True)
```
Note that `RMT_Util.py` also has an entrypoint in `fit_clipped_powerlaw()`.

Uses of the fit object are as follows:
 - Attributes:
   - `alpha`
   - `alphas`
   - `D`
   - `Ds`
   - `sigma`
   - `xmin`
   - `xmins`
   - `xmax`
   - `truncated_power_law.alpha`
   - `truncated_power_law.Lambda`
 - Methods:
   - `distribution_compare`
   - `plot_pdf`
   - `powerlaw.plot_pdf`
   - `truncated_power_law.plot_pdf`

Tests will also be needed to ensure that whatever `Fit` object is used conforms to this API.

**Comment by cdhinrichs** [comment]
A feasible set of steps might be:

- Move the function `pl_fit` from `weightwatcher.py` into a new file `WW_powerlaw.py`, without changing it.
- Write tests that check the API of fit objects returned by `pl_fit()`
- Implement a GPU version of the `Fit` object
- Implement the shim which sets `pl_fit()` to use the GPU version or not depending on torch / cuda availability.

**Comment by cdhinrichs** [comment]
Note that in the first iteration, only a standard power law distribution would be supported. Truncated power law would have to come later. Until then, truncated PL would have to default to the `powerlaw` package.

**Comment by cdhinrichs** [comment]
It turns out that the numpy implementation is faster overall (the problem is not large enough to benefit from making a round trip to the GPU,) but it is nevertheless much faster:
```
   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.001    0.001    4.309    4.309 weightwatcher.py:2061(analyze)
        3    0.000    0.000    3.508    1.169 weightwatcher.py:1890(apply_fit_powerlaw)
        3    0.001    0.000    3.508    1.169 weightwatcher.py:2666(fit_powerlaw)
        6    0.001    0.000    3.146    0.524 WW_powerlaw.py:122(pl_compare)
        6    0.000    0.000    3.145    0.524 WW_powerlaw.py:83(distribution_compare)
```

See PR #200 .

**Comment by cdhinrichs** [comment]
PR #200 has been merged, providing the desired speedup.
